from services.neo4j_database import Neo4jKG

def build_graph(pdf_path: str):
    triples = [
        ["Brain tumors", "are caused by", "uncontrolled growth of abnormal tissue"],
        ["Brain tumors", "can be", "benign"],
        ["Brain tumors", "can be", "malignant"],
        ["Malignant tumors", "contain", "active cancer cells"],
        ["Malignant tumors", "have", "irregular shapes"],
        ["Malignant tumors", "can spread to", "central nervous system"],
        ["Brain tumors", "can affect", "people of any age"],
        ["Early detection of tumors", "increases", "survival chances"],
        ["MRI", "stands for", "Magnetic Resonance Imaging"],
        ["MRI", "is used for", "visualizing human brain structures"],
        ["MRI", "uses", "multiple imaging techniques"],
        ["MRI scans", "are used to", "detect brain tumors"],
        ["MRI images", "contain", "brain tumor regions"],
        ["MRI brain images", "are used for", "tumor classification"],
        ["MRI brain images", "are used for", "tumor segmentation"],
        ["Brain tumor diagnosis", "is difficult due to", "complexity of human brain"],
        ["Segmentation", "divides", "image into regions"],
        ["Segmentation", "groups", "similar pixels"],
        ["Image segmentation", "uses", "color"],
        ["Image segmentation", "uses", "texture"],
        ["Image segmentation", "uses", "contrast"],
        ["Image segmentation", "uses", "boundaries"],

        ["The proposed method", "uses", "Discrete Wavelet Transform"],
        ["The proposed method", "uses", "Gray Level Co-occurrence Matrix"],
        ["The proposed method", "uses", "Principal Component Analysis"],
        ["The proposed method", "uses", "Probabilistic Neural Network"],
        ["The proposed method", "uses", "Kernel Support Vector Machine"],

        ["DWT", "stands for", "Discrete Wavelet Transform"],
        ["GLCM", "stands for", "Gray Level Co-occurrence Matrix"],
        ["PCA", "stands for", "Principal Component Analysis"],
        ["PNN", "stands for", "Probabilistic Neural Network"],
        ["KSVM", "stands for", "Kernel Support Vector Machine"],

        ["DWT", "is used for", "feature extraction"],
        ["GLCM", "is used for", "texture feature extraction"],
        ["PCA", "is used for", "dimensionality reduction"],
        ["PNN", "is used for", "classification"],
        ["KSVM", "is used for", "classification"],

        ["Feature extraction", "extracts", "texture features"],
        ["Feature extraction", "extracts", "statistical features"],
        ["Feature extraction", "extracts", "wavelet coefficients"],

        ["GLCM", "computes", "contrast"],
        ["GLCM", "computes", "correlation"],
        ["GLCM", "computes", "energy"],
        ["GLCM", "computes", "homogeneity"],
        ["GLCM", "computes", "entropy"],

        ["Texture analysis", "distinguishes", "normal tissue"],
        ["Texture analysis", "distinguishes", "abnormal tissue"],

        ["PCA", "reduces", "feature dimensionality"],
        ["PCA", "preserves", "data variance"],
        ["PCA", "improves", "classification efficiency"],

        ["Wavelet transform", "decomposes", "image into subbands"],
        ["Wavelet transform", "uses", "high pass filter"],
        ["Wavelet transform", "uses", "low pass filter"],
        ["Wavelet decomposition", "produces", "LL band"],
        ["Wavelet decomposition", "produces", "LH band"],
        ["Wavelet decomposition", "produces", "HL band"],
        ["Wavelet decomposition", "produces", "HH band"],

        ["Daubechies wavelet", "is used for", "image processing"],
        ["Daubechies wavelet", "is used in", "DWT decomposition"],
        ["The system", "uses", "five level wavelet decomposition"],

        ["GLCM", "is based on", "pixel intensity relationships"],
        ["GLCM", "measures", "spatial relationships"],
        ["GLCM", "generates", "2D histogram"],

        ["GLCM", "analyzes", "gray level distribution"],
        ["GLCM", "uses", "pixel pair relationships"],

        ["Feature vectors", "are generated from", "GLCM features"],
        ["Feature vectors", "are input to", "classifier"],

        ["PNN", "is", "feed forward neural network"],
        ["PNN", "is derived from", "Bayesian networks"],
        ["PNN", "is based on", "Kernel Fisher discriminant analysis"],

        ["PNN", "has layer", "input layer"],
        ["PNN", "has layer", "pattern layer"],
        ["PNN", "has layer", "summation layer"],
        ["PNN", "has layer", "output layer"],

        ["PNN", "computes", "distance between vectors"],
        ["PNN", "generates", "probability vector"],
        ["PNN", "classifies", "input sample"],

        ["The dataset", "contains", "MRI brain images"],
        ["Dataset", "includes", "normal brain images"],
        ["Dataset", "includes", "abnormal brain images"],

        ["Dataset", "contains", "Alzheimer disease images"],
        ["Dataset", "contains", "glioma images"],
        ["Dataset", "contains", "meningioma images"],
        ["Dataset", "contains", "visual agnosia images"],
        ["Dataset", "contains", "Pick disease images"],
        ["Dataset", "contains", "Huntington disease images"],
        ["Dataset", "contains", "sarcoma images"],

        ["Dataset", "uses", "T2 weighted MRI images"],

        ["OASIS dataset", "provides", "MRI images"],
        ["ADNI dataset", "provides", "MRI images"],

        ["MRI dataset", "contains", "260 images"],

        ["Classification", "categorizes", "normal brain"],
        ["Classification", "categorizes", "abnormal brain"],

        ["Classification", "uses", "SVM kernels"],
        ["SVM kernels", "include", "Linear kernel"],
        ["SVM kernels", "include", "Polynomial kernel"],
        ["SVM kernels", "include", "RBF kernel"],

        ["GRB kernel", "achieves", "best classification accuracy"],
        ["Proposed method", "achieves", "99.38 percent accuracy"],
        ["Proposed KSVM method", "achieves", "99.61 percent accuracy"],

        ["Existing method SOM+DWT", "achieves", "95 percent accuracy"],
        ["Existing method SVM+DWT", "achieves", "96 percent accuracy"],
        ["Existing method PCA+ANN+DWT", "achieves", "97 percent accuracy"],
        ["Existing method PCA+ACPSO+FNN+DWT", "achieves", "98.75 percent accuracy"],

        ["Noise removal", "is part of", "preprocessing"],
        ["Preprocessing", "improves", "signal to noise ratio"],

        ["Noise", "can occur during", "image acquisition"],
        ["Noise", "can occur during", "image transmission"],
        ["Noise", "can occur during", "image compression"],

        ["Segmentation", "detects", "tumor region"],
        ["Segmentation", "localizes", "tumor area"],

        ["Classification system", "distinguishes", "normal tissue"],
        ["Classification system", "distinguishes", "tumor tissue"],

        ["Tumor classification", "helps", "medical diagnosis"],
        ["Tumor detection", "assists", "physicians"],

        ["Brain tumor classification", "uses", "MRI imaging"],
        ["MRI imaging", "provides", "internal brain features"],

        ["Experimental setup", "uses", "Intel i7 processor"],
        ["Experimental setup", "uses", "32GB RAM"],
        ["Experimental setup", "runs on", "Windows 10"],

        ["Algorithm implementation", "uses", "MATLAB 2018"],
        ["Algorithm implementation", "uses", "Wavelet toolbox"],
        ["Algorithm implementation", "uses", "SVM toolbox"],

        ["Classifier evaluation", "uses", "accuracy"],
        ["Classifier evaluation", "uses", "PSNR"],
        ["Classifier evaluation", "uses", "MSE"],

        ["Tumor segmentation", "outputs", "tumor region area"],
        ["Tumor detection", "outputs", "tumor location"],
        
        ["Brain Tumor MRI Identification and Classification", "uses", "DWT"],
        ["Brain Tumor MRI Identification and Classification", "uses", "PCA"],
        ["Brain Tumor MRI Identification and Classification", "uses", "KSVM"],
        ["Brain Tumor MRI Identification and Classification", "published in", "IEEE Transactions on Medical Imaging"],
        ["Brain Tumor MRI Identification and Classification", "published in", "TechRxiv"],
        ["Brain Tumor MRI Identification and Classification", "published on", "December 2022"],
        ["Brain Tumor MRI Identification and Classification", "authored by", "Omar Faruq"],
        ["Brain Tumor MRI Identification and Classification", "authored by", "Islam Md Jahidul"],
        ["Brain Tumor MRI Identification and Classification", "authored by", "Md. Sakib Ahmed"],
        ["Brain Tumor MRI Identification and Classification", "authored by", "Md Sajib Hossain"],

        ["Omar Faruq", "affiliated with", "Chongqing University of Posts and Telecommunications"],
        ["Omar Faruq", "affiliated with", "School of Communication and Information Engineering"],
        ["Omar Faruq", "affiliated with", "Saic Institute of Management and Technology Bangladesh"],
        ["Omar Faruq", "role at", "Head of Department of Electronics and Telecommunication Engineering"],
        ["Omar Faruq", "graduated from", "Daffodil International University"],
        ["Omar Faruq", "degree in", "Electrical and Electronic Engineering"],
        ["Omar Faruq", "post-graduate from", "Chongqing University of Posts and Telecommunications"],
        ["Omar Faruq", "researches", "Free-Space Optical Communication"],
        ["Omar Faruq", "researches", "Optical Fiber Communication"],
        ["Omar Faruq", "researches", "Image and Signal Processing"],
        ["Omar Faruq", "researches", "Nano-Optics"],
        ["Omar Faruq", "researches", "Computer Vision"],
        ["Omar Faruq", "researches", "Machine Learning"],
        ["Omar Faruq", "ORCID", "0000-0002-4901-2753"],
        ["Omar Faruq", "email", "smomarfaruq99@gmail.com"],

        ["Islam Md Jahidul", "affiliated with", "Northeastern University"],
        ["Islam Md Jahidul", "affiliated with", "School of Software Engineering"],
        ["Islam Md Jahidul", "graduated from", "Chongqing University of Posts and Telecommunications"],
        ["Islam Md Jahidul", "status", "post-graduate student"],
        ["Islam Md Jahidul", "researches", "Computer Vision"],
        ["Islam Md Jahidul", "researches", "Image Processing"],
        ["Islam Md Jahidul", "researches", "Signal Processing"],
        ["Islam Md Jahidul", "researches", "Artificial Intelligence"],
        ["Islam Md Jahidul", "researches", "Machine Learning"],
        ["Islam Md Jahidul", "researches", "Deep Learning"],
        ["Islam Md Jahidul", "researches", "Neural Networks"],
        ["Islam Md Jahidul", "ORCID", "0000-0002-6847-1808"],
        ["Islam Md Jahidul", "email", "jahidulislamneu@gmail.com"],

        ["Md. Sakib Ahmed", "affiliated with", "Green University Bangladesh"],
        ["Md. Sakib Ahmed", "department", "Electrical and Electronic Engineering"],
        ["Md. Sakib Ahmed", "status", "graduate student"],
        ["Md. Sakib Ahmed", "researches", "Image Processing"],
        ["Md. Sakib Ahmed", "researches", "Bio-medical"],
        ["Md. Sakib Ahmed", "researches", "Bio-informatics"],
        ["Md. Sakib Ahmed", "ORCID", "0000-0002-4950-4539"],
        ["Md. Sakib Ahmed", "email", "sakibahmed1046@gmail.com"],

        ["Md Sajib Hossain", "affiliated with", "Green University Bangladesh"],
        ["Md Sajib Hossain", "department", "Electrical and Electronic Engineering"],
        ["Md Sajib Hossain", "status", "graduate student"],
        ["Md Sajib Hossain", "researches", "Image Processing"],
        ["Md Sajib Hossain", "researches", "Bio-medical"],
        ["Md Sajib Hossain", "researches", "Bio-informatics"],
        ["Md Sajib Hossain", "ORCID", "0000-0003-2590-5095"],
        ["Md Sajib Hossain", "email", "sajibhossaincpi@gmail.com"],

        ["Brain Tumor", "caused by", "uncontrolled growth of aberrant malignant tissue"],
        ["Brain Tumor", "type", "Benign"],
        ["Brain Tumor", "type", "Malignant"],
        ["Brain Tumor", "is", "primary cause of mortality"],
        ["Brain Tumor", "can affect", "people of any age"],
        ["Brain Tumor", "can affect", "central nervous system (CNS)"],
        ["Brain Tumor", "graded by", "Grade I to Grade IV grading system"],

        ["Benign Tumor", "contains", "cancer cells unrelated to tumor"],
        ["Benign Tumor", "characterized by", "physically equivalent cells"],
        ["Benign Tumor", "graded as", "Grade I or Grade II"],

        ["Malignant Tumor", "contains", "active cancer cells"],
        ["Malignant Tumor", "characterized by", "irregularly shaped features"],
        ["Malignant Tumor", "can spread to", "all sections of CNS"],
        ["Malignant Tumor", "graded as", "Grade III or Grade IV"],
        ["Malignant Tumor", "is", "rapidly developing"],
        ["Malignant Tumor", "damages", "proper brain cells"],

        ["Grade I Tumor", "is", "lesser grade"],
        ["Grade II Tumor", "is", "lesser grade"],
        ["Grade III Tumor", "is", "greater grade"],
        ["Grade IV Tumor", "is", "greater grade"],

        ["MRI", "stands for", "Magnetic Resonance Imaging"],
        ["MRI", "used for", "evaluating human brain interior features"],
        ["MRI", "used for", "distinguishing neurological structures"],
        ["MRI", "used for", "brain tumor detection"],
        ["MRI", "modality type used", "T2-weighted"],
        ["MRI", "preferred modality", "T2 over T1 and PET"],
        ["MRI", "image resolution", "256 albums"],
        ["MRI", "image size", "256x256 pixels"],

        ["Proposed Method", "has steps", "5 major steps"],
        ["Proposed Method", "step 1", "Feature Extraction using DWT"],
        ["Proposed Method", "step 2", "Texture Extraction using GLCM"],
        ["Proposed Method", "step 3", "Feature Selection using PCA"],
        ["Proposed Method", "step 4", "Tumor Detection and K-means structural analysis"],
        ["Proposed Method", "step 5", "PNN-RBF Network Identification"],
        ["Proposed Method", "implemented in", "MATLAB 2018"],
        ["Proposed Method", "tested on", "Intel i7 platform"],
        ["Proposed Method", "processor speed", "5.0GHz"],
        ["Proposed Method", "RAM", "32 GB"],
        ["Proposed Method", "operating system", "Windows 10"],
        ["Proposed Method", "uses toolbox", "MATLAB Wavelet Toolbox"],
        ["Proposed Method", "uses toolbox", "MATLAB 2018 Bio Statistical Toolbox"],

        ["DWT", "stands for", "Discrete Wavelet Transform"],
        ["DWT", "used for", "feature extraction"],
        ["DWT", "used for", "noise removal"],
        ["DWT", "used for", "image segmentation"],
        ["DWT", "decomposes into", "LL sub-band"],
        ["DWT", "decomposes into", "HL sub-band"],
        ["DWT", "decomposes into", "LH sub-band"],
        ["DWT", "decomposes into", "HH sub-band"],
        ["DWT", "uses filter", "High Pass Filter (Ho_D)"],
        ["DWT", "uses filter", "Low Pass Filter (Lo_D)"],
        ["DWT", "wavelet used", "Daubechies wavelet (db4)"],
        ["DWT", "decomposition levels", "5 levels"],
        ["DWT", "best sub-band performance", "LH over HL sub-band"],
        ["DWT", "analyzes", "frequency components"],
        ["DWT", "mathematical formula", "w_psi(a,b) = integral f(x) * psi_ab(t) dx"],
        ["DWT", "parameters", "dilation factor a and translation parameter b"],
        ["DWT", "derived from", "mother wavelet"],

        ["Daubechies Wavelet (db4)", "considered", "best quality for image utility"],
        ["Daubechies Wavelet (db4)", "type", "discrete wavelet"],

        ["GLCM", "stands for", "Gray Level Co-occurrence Matrix"],
        ["GLCM", "also known as", "Gray Level Spatial Dependence Matrix (GLSDM)"],
        ["GLCM", "used for", "texture feature extraction"],
        ["GLCM", "extracts feature", "Contrast"],
        ["GLCM", "extracts feature", "Correlation"],
        ["GLCM", "extracts feature", "Energy"],
        ["GLCM", "extracts feature", "Homogeneity"],
        ["GLCM", "extracts feature", "Entropy"],
        ["GLCM", "is", "two-dimensional histogram"],
        ["GLCM", "interval feature", "d=1"],
        ["GLCM", "perspectives", "45, 90, 135 degrees"],
        ["GLCM", "based on", "Haralick's statistical technique"],
        ["GLCM", "applied to", "LH and HL sub-bands"],
        ["GLCM", "distinguishes", "regular and anomalous tissue"],

        ["PCA", "stands for", "Principal Component Analysis"],
        ["PCA", "used for", "feature selection"],
        ["PCA", "used for", "dimensionality reduction"],
        ["PCA", "used for", "reducing wavelet coefficient complexity"],
        ["PCA", "preserves", "replicated data variance"],
        ["PCA", "reduces", "feature vector from 10245 to 7"],
        ["PCA", "results in", "more descriptive and precise classification"],

        ["PNN", "stands for", "Probabilistic Neural Network"],
        ["PNN", "type", "feed-forward neural network"],
        ["PNN", "derived from", "Bayesian network"],
        ["PNN", "derived from", "Kernel Fisher discriminatory analysis"],
        ["PNN", "implemented by", "D.F. Specht"],
        ["PNN", "founded in", "early 1990s"],
        ["PNN", "architecture layers", "Input layer"],
        ["PNN", "architecture layers", "Pattern/Summation layer"],
        ["PNN", "architecture layers", "Output layer"],
        ["PNN", "architecture layers", "Hidden layer"],
        ["PNN", "used for", "brain tumor classification"],
        ["PNN", "used for", "training and testing MRI images"],
        ["PNN", "output", "1 for matched class, 0 for non-matched"],

        ["KSVM", "stands for", "Kernel Support Vector Machine"],
        ["KSVM", "uses kernel", "Linear (LIN)"],
        ["KSVM", "uses kernel", "Homogeneous Polynomial (HPOL)"],
        ["KSVM", "uses kernel", "Inhomogeneous Polynomial (IPOL)"],
        ["KSVM", "uses kernel", "Gaussian RBF (GRB)"],
        ["KSVM", "best kernel", "GRB (Gaussian RBF)"],
        ["KSVM", "SVM with linear kernel called", "KSVM"],
        ["KSVM", "used for", "MR brain image classification"],

        ["GRB Kernel SVM", "achieves accuracy", "99.61%"],
        ["GRB Kernel SVM", "outperforms", "HPOL kernel SVM"],
        ["GRB Kernel SVM", "outperforms", "IPOL kernel SVM"],
        ["GRB Kernel SVM", "outperforms", "LIN kernel SVM"],
        ["GRB Kernel SVM", "confusion matrix Normal-Normal", "20"],
        ["GRB Kernel SVM", "confusion matrix Normal-Abnormal", "1"],
        ["GRB Kernel SVM", "confusion matrix Abnormal-Normal", "0"],
        ["GRB Kernel SVM", "confusion matrix Abnormal-Abnormal", "239"],

        ["LIN Kernel SVM", "achieves accuracy", "95.38%"],
        ["LIN Kernel SVM", "confusion matrix Normal-Normal", "18"],
        ["LIN Kernel SVM", "confusion matrix Normal-Abnormal", "5"],
        ["LIN Kernel SVM", "confusion matrix Abnormal-Normal", "3"],
        ["LIN Kernel SVM", "confusion matrix Abnormal-Abnormal", "230"],

        ["HPOL Kernel SVM", "achieves accuracy", "96.53%"],
        ["HPOL Kernel SVM", "confusion matrix Normal-Normal", "19"],
        ["HPOL Kernel SVM", "confusion matrix Normal-Abnormal", "4"],
        ["HPOL Kernel SVM", "confusion matrix Abnormal-Normal", "1"],
        ["HPOL Kernel SVM", "confusion matrix Abnormal-Abnormal", "232"],

        ["IPOL Kernel SVM", "achieves accuracy", "98.88%"],
        ["IPOL Kernel SVM", "confusion matrix Normal-Normal", "18"],
        ["IPOL Kernel SVM", "confusion matrix Normal-Abnormal", "1"],
        ["IPOL Kernel SVM", "confusion matrix Abnormal-Normal", "2"],
        ["IPOL Kernel SVM", "confusion matrix Abnormal-Abnormal", "239"],

        ["DWT+PCA+KSVM", "overall best accuracy", "99.61% (GRB kernel)"],
        ["DWT+PCA+KSVM", "total images tested", "260"],
        ["DWT+PCA+KSVM", "outperforms", "SOM+DWT"],
        ["DWT+PCA+KSVM", "outperforms", "SVM+DWT with linear kernel"],
        ["DWT+PCA+KSVM", "outperforms", "SVM+DWT with RBF kernel"],
        ["DWT+PCA+KSVM", "outperforms", "PCA+KNN+DWT"],
        ["DWT+PCA+KSVM", "outperforms", "PCA+ANN+DWT"],
        ["DWT+PCA+KSVM", "outperforms", "PCA+ACPSO+FNN+DWT"],

        ["SOM+DWT", "accuracy", "95%"],
        ["SVM+DWT with linear kernel", "accuracy", "96%"],
        ["SVM+DWT with RBF based kernel", "accuracy", "98%"],
        ["PCA+KNN+DWT", "accuracy", "98%"],
        ["PCA+ANN+DWT", "accuracy", "97%"],
        ["PCA+ACPSO+FNN+DWT", "accuracy", "98.75%"],

        ["Dataset", "sourced from", "OASIS"],
        ["Dataset", "sourced from", "ADNI"],
        ["Dataset", "MRI type", "axial T2-weighted MR pictures"],
        ["Dataset", "total images", "160"],
        ["Dataset", "normal brain images", "20"],
        ["Dataset", "abnormal brain images", "140"],
        ["Dataset", "images per category", "20"],
        ["Dataset", "normal brain categories", "1"],
        ["Dataset", "abnormal brain categories", "7"],
        ["Dataset", "disease class", "Alzheimer's disease"],
        ["Dataset", "disease class", "Glioma"],
        ["Dataset", "disease class", "Meningioma"],
        ["Dataset", "disease class", "Visual Agnosia"],
        ["Dataset", "disease class", "Pick's disease"],
        ["Dataset", "disease class", "Huntington's disease"],
        ["Dataset", "disease class", "Sarcoma"],

        ["Image Pre-processing", "includes", "Noise removal"],
        ["Image Pre-processing", "includes", "Filtering"],
        ["Image Pre-processing", "includes", "De-noising"],
        ["Image Pre-processing", "purpose", "eliminate noise from images"],
        ["Image Pre-processing", "purpose", "increase signal-to-noise ratio"],
        ["Image Pre-processing", "uses", "Morphological filtering"],

        ["Image Segmentation", "is", "process of splitting image into distinct segments"],
        ["Image Segmentation", "types", "Feature Based"],
        ["Image Segmentation", "types", "Threshold Based"],
        ["Image Segmentation", "types", "Model Based"],
        ["Image Segmentation", "types", "Region Based"],
        ["Image Segmentation", "types", "Gray Scale"],
        ["Image Segmentation", "types", "Edge Detection Based"],
        ["Image Segmentation", "sub-type", "Feature Selection"],
        ["Image Segmentation", "sub-type", "Feature Extraction"],
        ["Image Segmentation", "sub-type", "LOG"],
        ["Image Segmentation", "sub-type", "Canny"],
        ["Image Segmentation", "sub-type", "Sobel"],
        ["Image Segmentation", "sub-type", "Laplacian"],
        ["Image Segmentation", "sub-type", "Rebort"],
        ["Image Segmentation", "sub-type", "Gradient"],

        ["Image Classification", "types", "Pixel-wise Image Classification"],
        ["Image Classification", "types", "Object-Based Image Classification"],
        ["Image Classification", "types", "Sub Pixel-wise Image Classification"],
        ["Image Classification", "approach", "Supervised Classification"],
        ["Image Classification", "approach", "Unsupervised Classification"],
        ["Image Classification", "supervised methods", "SVM"],
        ["Image Classification", "supervised methods", "Maximum Likelihood"],
        ["Image Classification", "supervised methods", "Minimum Distance"],
        ["Image Classification", "unsupervised methods", "K-means"],
        ["Image Classification", "unsupervised methods", "ISO Data"],
        ["Image Classification", "unsupervised methods", "SOM"],

        ["Feature Extraction", "retrieves", "statistical data from image"],
        ["Feature Extraction", "extracts", "color characteristics"],
        ["Feature Extraction", "extracts", "texture"],
        ["Feature Extraction", "extracts", "shape"],
        ["Feature Extraction", "extracts", "contrast"],
        ["Feature Extraction", "uses", "DWT"],
        ["Feature Extraction", "uses", "GLCM"],

        ["GLCM Training Data - Pic1", "Contrast", "0.386541"],
        ["GLCM Training Data - Pic1", "Correlation", "0.0805"],
        ["GLCM Training Data - Pic1", "Energy", "0.81568"],
        ["GLCM Training Data - Pic1", "Homogeneity", "0.900"],
        ["GLCM Training Data - Pic1", "Entropy", "2.3224"],

        ["GLCM Training Data - Pic2", "Contrast", "0.360122"],
        ["GLCM Training Data - Pic2", "Correlation", "0.1725"],
        ["GLCM Training Data - Pic2", "Energy", "0.81607"],
        ["GLCM Training Data - Pic2", "Homogeneity", "0.9474"],
        ["GLCM Training Data - Pic2", "Entropy", "0.2244"],

        ["GLCM Training Data - Pic3", "Contrast", "0.265017"],
        ["GLCM Training Data - Pic3", "Correlation", "0.1248"],
        ["GLCM Training Data - Pic3", "Energy", "0.77808"],
        ["GLCM Training Data - Pic3", "Homogeneity", "0.9383"],
        ["GLCM Training Data - Pic3", "Entropy", "2.8746"],

        ["GLCM Training Data - Pic4", "Contrast", "0.315628"],
        ["GLCM Training Data - Pic4", "Correlation", "0.0928"],
        ["GLCM Training Data - Pic4", "Energy", "0.79636"],
        ["GLCM Training Data - Pic4", "Homogeneity", "0.9404"],
        ["GLCM Training Data - Pic4", "Entropy", "2.6739"],

        ["GLCM Training Data - Pic5", "Contrast", "0.365406"],
        ["GLCM Training Data - Pic5", "Correlation", "0.1353"],
        ["GLCM Training Data - Pic5", "Energy", "0.80855"],
        ["GLCM Training Data - Pic5", "Homogeneity", "0.9447"],
        ["GLCM Training Data - Pic5", "Entropy", "2.5116"],

        ["GLCM Training Data - Pic6", "Contrast", "0.285873"],
        ["GLCM Training Data - Pic6", "Correlation", "0.1143"],
        ["GLCM Training Data - Pic6", "Energy", "0.75812"],
        ["GLCM Training Data - Pic6", "Homogeneity", "0.9315"],
        ["GLCM Training Data - Pic6", "Entropy", "2.8806"],

        ["GLCM Training Data - Pic7", "Contrast", "0.299221"],
        ["GLCM Training Data - Pic7", "Correlation", "0.1129"],
        ["GLCM Training Data - Pic7", "Energy", "0.78455"],
        ["GLCM Training Data - Pic7", "Homogeneity", "0.9387"],
        ["GLCM Training Data - Pic7", "Entropy", "2.9101"],

        ["GLCM Training Data - Pic8", "Contrast", "0.267241"],
        ["GLCM Training Data - Pic8", "Correlation", "0.1246"],
        ["GLCM Training Data - Pic8", "Energy", "0.77884"],
        ["GLCM Training Data - Pic8", "Homogeneity", "0.9367"],
        ["GLCM Training Data - Pic8", "Entropy", "2.9114"],

        ["GLCM Testing Data - Pic1", "Contrast", "0.2755"],
        ["GLCM Testing Data - Pic1", "Correlation", "0.106333"],
        ["GLCM Testing Data - Pic1", "Energy", "0.72044"],
        ["GLCM Testing Data - Pic1", "Homogeneity", "0.92139"],
        ["GLCM Testing Data - Pic1", "Entropy", "3.3209"],

        ["GLCM Testing Data - Pic2", "Contrast", "0.2611"],
        ["GLCM Testing Data - Pic2", "Correlation", "0.129665"],
        ["GLCM Testing Data - Pic2", "Energy", "0.76435"],
        ["GLCM Testing Data - Pic2", "Homogeneity", "0.93428"],
        ["GLCM Testing Data - Pic2", "Entropy", "3.3830"],

        ["GLCM Testing Data - Pic3", "Contrast", "0.2611"],
        ["GLCM Testing Data - Pic3", "Correlation", "0.129665"],
        ["GLCM Testing Data - Pic3", "Energy", "0.76435"],
        ["GLCM Testing Data - Pic3", "Homogeneity", "0.93428"],
        ["GLCM Testing Data - Pic3", "Entropy", "3.2821"],

        ["GLCM Testing Data - Pic4", "Contrast", "0.2929"],
        ["GLCM Testing Data - Pic4", "Correlation", "0.156369"],
        ["GLCM Testing Data - Pic4", "Energy", "0.82164"],
        ["GLCM Testing Data - Pic4", "Homogeneity", "0.94967"],
        ["GLCM Testing Data - Pic4", "Entropy", "2.7610"],

        ["GLCM Testing Data - Pic5", "Contrast", "0.2469"],
        ["GLCM Testing Data - Pic5", "Correlation", "0.07749"],
        ["GLCM Testing Data - Pic5", "Energy", "0.74696"],
        ["GLCM Testing Data - Pic5", "Homogeneity", "0.92848"],
        ["GLCM Testing Data - Pic5", "Entropy", "3.3895"],

        ["GLCM Testing Data - Pic6", "Contrast", "0.2416"],
        ["GLCM Testing Data - Pic6", "Correlation", "0.177739"],
        ["GLCM Testing Data - Pic6", "Energy", "0.77415"],
        ["GLCM Testing Data - Pic6", "Homogeneity", "0.9373"],
        ["GLCM Testing Data - Pic6", "Entropy", "2.5186"],

        ["GLCM Testing Data - Pic7", "Contrast", "0.2611"],
        ["GLCM Testing Data - Pic7", "Correlation", "0.12966"],
        ["GLCM Testing Data - Pic7", "Energy", "0.76435"],
        ["GLCM Testing Data - Pic7", "Homogeneity", "0.93428"],
        ["GLCM Testing Data - Pic7", "Entropy", "3.2820"],

        ["GLCM Testing Data - Pic8", "Contrast", "0.3053"],
        ["GLCM Testing Data - Pic8", "Correlation", "0.09188"],
        ["GLCM Testing Data - Pic8", "Energy", "0.7674"],
        ["GLCM Testing Data - Pic8", "Homogeneity", "0.9326"],
        ["GLCM Testing Data - Pic8", "Entropy", "2.9181"],

        ["Tumor Extraction - Pic1", "PSNR", "13.011"],
        ["Tumor Extraction - Pic1", "MSE", "5.121"],
        ["Tumor Extraction - Pic1", "Area of Picture (pixels)", "38240"],
        ["Tumor Extraction - Pic1", "Area of Tumor Region", "7598"],

        ["Tumor Extraction - Pic2", "PSNR", "12.82"],
        ["Tumor Extraction - Pic2", "MSE", "2.116"],
        ["Tumor Extraction - Pic2", "Area of Picture (pixels)", "66824"],
        ["Tumor Extraction - Pic2", "Area of Tumor Region", "9774"],

        ["Tumor Extraction - Pic3", "PSNR", "13.12"],
        ["Tumor Extraction - Pic3", "MSE", "6.068"],
        ["Tumor Extraction - Pic3", "Area of Picture (pixels)", "49508"],
        ["Tumor Extraction - Pic3", "Area of Tumor Region", "7532"],

        ["Tumor Extraction - Pic4", "PSNR", "14.86"],
        ["Tumor Extraction - Pic4", "MSE", "5.77"],
        ["Tumor Extraction - Pic4", "Area of Picture (pixels)", "49388"],
        ["Tumor Extraction - Pic4", "Area of Tumor Region", "8956"],

        ["Tumor Extraction - Pic5", "PSNR", "12.79"],
        ["Tumor Extraction - Pic5", "MSE", "4.84"],
        ["Tumor Extraction - Pic5", "Area of Picture (pixels)", "23964"],
        ["Tumor Extraction - Pic5", "Area of Tumor Region", "4465"],

        ["Tumor Extraction - Pic6", "PSNR", "12.82"],
        ["Tumor Extraction - Pic6", "MSE", "6.79"],
        ["Tumor Extraction - Pic6", "Area of Picture (pixels)", "49429"],
        ["Tumor Extraction - Pic6", "Area of Tumor Region", "3598"],

        ["Tumor Extraction - Pic7", "PSNR", "12.99"],
        ["Tumor Extraction - Pic7", "MSE", "5.92"],
        ["Tumor Extraction - Pic7", "Area of Picture (pixels)", "49298"],
        ["Tumor Extraction - Pic7", "Area of Tumor Region", "5979"],

        ["Tumor Extraction - Pic8", "PSNR", "13.004"],
        ["Tumor Extraction - Pic8", "MSE", "6.35"],
        ["Tumor Extraction - Pic8", "Area of Picture (pixels)", "34040"],
        ["Tumor Extraction - Pic8", "Area of Tumor Region", "12932"],

        ["K-means", "used for", "structural analysis of tumor"],
        ["K-means", "type", "unsupervised classification"],

        ["Computer-Assisted Diagnostic Algorithm", "developed to replace", "invasive diagnostic techniques"],
        ["Computer-Assisted Diagnostic Algorithm", "developed to replace", "biopsies"],
        ["Computer-Assisted Diagnostic Algorithm", "developed to replace", "lumbar punctures"],
        ["Computer-Assisted Diagnostic Algorithm", "developed to replace", "spinal tap movements"],
        ["Computer-Assisted Diagnostic Algorithm", "classifies", "common genius tumors"],
        ["Computer-Assisted Diagnostic Algorithm", "classifies", "non-cancerous tumor"],
        ["Computer-Assisted Diagnostic Algorithm", "classifies", "malignant tumor"],

        ["Proposed System", "achieved accuracy on training data", "~100%"],
        ["Proposed System", "achieved accuracy on testing data", "~95%"],
        ["Proposed System", "performs", "precise brain tumor detection"],
        ["Proposed System", "performs", "tumor site localization"],
        ["Proposed System", "improves", "PSNR metric"],
        ["Proposed System", "improves", "MSE metric"],
        ["Proposed System", "faster than", "manual medical professional diagnosis"],
        ["Proposed System", "more accurate than", "manual medical professional diagnosis"],

        ["Wavelet Decomposition", "is", "phase 1 of proposed method"],
        ["Texture Extraction", "is", "phase 2 of proposed method"],
        ["Classification", "is", "phase 3 of proposed method"],

        ["Early Brain Tumor Detection", "increases", "patient survival chances"],
        ["Early Brain Tumor Detection", "enables", "monitoring malignant cell regions"],
        ["Early Brain Tumor Detection", "enables", "reliable diagnoses"],
        ["Early Brain Tumor Detection", "helps decide", "radiation therapy"],
        ["Early Brain Tumor Detection", "helps decide", "surgery"],
        ["Early Brain Tumor Detection", "helps decide", "chemotherapy"],

        ["Image Processing", "used for", "segmentation of tumor regions"],
        ["Image Processing", "properties used for segmentation", "color"],
        ["Image Processing", "properties used for segmentation", "texture"],
        ["Image Processing", "properties used for segmentation", "contrast"],
        ["Image Processing", "properties used for segmentation", "borders"],

        ["SVM Toolbox", "type", "free toolbox"],
        ["SVM Toolbox", "used in", "MATLAB"],
        ["SVM Toolbox", "purpose", "expand SVM kernel for MR image classification"],

        ["Software Used", "includes", "MATLAB"],
        ["Software Used", "includes", "C programming language"],
        ["Software Used", "purpose", "code, schematics, and simulations"],

        ["Funding", "status", "No funding received"],
        ["Paper", "received no funding from", "any external source"],

        ["Reference 1 - Varuna Shree", "topic", "Brain tumor MRI classification using DWT and PNN"],
        ["Reference 1 - Varuna Shree", "published in", "Brain Informatics"],
        ["Reference 1 - Varuna Shree", "year", "2018"],
        ["Reference 1 - Varuna Shree", "volume", "5(1)"],
        ["Reference 1 - Varuna Shree", "pages", "23-30"],

        ["Reference 2 - Sharma and Singh", "topic", "Image denoising using spatial domain filters"],
        ["Reference 2 - Sharma and Singh", "published in", "CISP 2013"],
        ["Reference 2 - Sharma and Singh", "year", "2013"],

        ["Reference 3 - Ghahfarrokhi and Khodadadi", "topic", "Human brain tumor diagnosis using complexity and texture features via MRI"],
        ["Reference 3 - Ghahfarrokhi and Khodadadi", "published in", "Biomedical Signal Processing and Control"],
        ["Reference 3 - Ghahfarrokhi and Khodadadi", "year", "2020"],
        ["Reference 3 - Ghahfarrokhi and Khodadadi", "volume", "61"],
        ["Reference 3 - Ghahfarrokhi and Khodadadi", "article ID", "102025"],

        ["Reference 4 - Kwak and Choi", "topic", "Input feature selection for classification problems"],
        ["Reference 4 - Kwak and Choi", "published in", "IEEE Transactions on Neural Networks"],
        ["Reference 4 - Kwak and Choi", "year", "2002"],
        ["Reference 4 - Kwak and Choi", "volume", "13(1)"],
        ["Reference 4 - Kwak and Choi", "pages", "143-159"],

        ["Reference 5 - Amin et al.", "topic", "Brain Tumor Classification: Feature Fusion"],
        ["Reference 5 - Amin et al.", "published in", "ICCIS 2019"],
        ["Reference 5 - Amin et al.", "year", "2019"],

        ["Reference 6 - Ayadi et al.", "topic", "Hybrid feature extraction for brain MRI classification using Bag-of-Words"],
        ["Reference 6 - Ayadi et al.", "published in", "Biomedical Signal Process Control"],
        ["Reference 6 - Ayadi et al.", "year", "2019"],
        ["Reference 6 - Ayadi et al.", "volume", "48"],
        ["Reference 6 - Ayadi et al.", "pages", "144-152"],

        ["Reference 7 - Nagtode et al.", "topic", "2D DWT and PNN for brain tumor detection and classification"],
        ["Reference 7 - Nagtode et al.", "published in", "ICECCS 2016"],
        ["Reference 7 - Nagtode et al.", "year", "2016"],
        ["Reference 7 - Nagtode et al.", "pages", "20-26"],

        ["Reference 8 - Mathew and Anto", "topic", "Tumor detection and classification of MRI brain image using wavelet transform and SVM"],
        ["Reference 8 - Mathew and Anto", "published in", "ICSPC 2017"],
        ["Reference 8 - Mathew and Anto", "year", "2017"],
        ["Reference 8 - Mathew and Anto", "pages", "75-78"],

        ["Reference 9 - Mao et al.", "topic", "Probabilistic neural-network structure for pattern classification"],
        ["Reference 9 - Mao et al.", "published in", "IEEE Transactions on Neural Networks"],
        ["Reference 9 - Mao et al.", "year", "2000"],
        ["Reference 9 - Mao et al.", "volume", "11(4)"],
        ["Reference 9 - Mao et al.", "pages", "1009-1016"],

        ["Reference 10 - Bahadure et al.", "topic", "Image Analysis for MRI Based Brain Tumor Detection using BWT and SVM"],
        ["Reference 10 - Bahadure et al.", "published in", "Hindawi International Journal of Biomedical Imaging"],
        ["Reference 10 - Bahadure et al.", "year", "2017"],
        ["Reference 10 - Bahadure et al.", "article ID", "9749108"],

        ["Reference 11 - Sabitha et al.", "topic", "MRI brain tumor detection and classification using KPCA and KSVM"],
        ["Reference 11 - Sabitha et al.", "year", "2021"],

        ["Reference 13 - Rao and Karunakara", "topic", "Efficient Detection and Classification of Brain Tumor using Kernel based SVM for MRI"],
        ["Reference 13 - Rao and Karunakara", "published in", "Multimedia Tools and Applications"],
        ["Reference 13 - Rao and Karunakara", "year", "2022"],
        ["Reference 13 - Rao and Karunakara", "volume", "81"],
        ["Reference 13 - Rao and Karunakara", "pages", "7393-7417"],

        ["Reference 14 - Kumar and Devi", "topic", "Brain tumor detection using texture features and SVM in MR images"],
        ["Reference 14 - Kumar and Devi", "published in", "Asian Pacific Journal of Cancer Prevention"],
        ["Reference 14 - Kumar and Devi", "year", "2018"],
        ["Reference 14 - Kumar and Devi", "volume", "19(1)"],
        ["Reference 14 - Kumar and Devi", "pages", "2789-2794"],

        ["Reference 15 - Mehekare and Ganorkar", "topic", "Detection of brain tumor using DWT, PCA and KSVM"],
        ["Reference 15 - Mehekare and Ganorkar", "published in", "International Journal of Innovative Research in Computer and Communication Engineering"],
        ["Reference 15 - Mehekare and Ganorkar", "year", "2017"],
        ["Reference 15 - Mehekare and Ganorkar", "volume", "5(5)"],

        ["Reference 16 - Mandle et al.", "topic", "Brain Tumor Segmentation and Classification in MRI using Clustering and Kernel-Based SVM"],
        ["Reference 16 - Mandle et al.", "published in", "Biomedicine and Pharmacology Journal"],
        ["Reference 16 - Mandle et al.", "year", "2022"],
        ["Reference 16 - Mandle et al.", "volume", "15(2)"],

        ["Reference 17 - Islam and Faruq", "topic", "Further Exploration of Deep Aggregation for Shadow Detection"],
        ["Reference 17 - Islam and Faruq", "published in", "Modern Innovations Systems and Technologies"],
        ["Reference 17 - Islam and Faruq", "year", "2022"],
        ["Reference 17 - Islam and Faruq", "volume", "2(3)"],
        ["Reference 17 - Islam and Faruq", "pages", "0312-0330"],

        ["Reference 18 - Saouli et al.", "topic", "Fully automatic brain tumor segmentation using deep neural networks in MRI images"],
        ["Reference 18 - Saouli et al.", "published in", "Computer Methods Programs Biomedicine"],
        ["Reference 18 - Saouli et al.", "year", "2018"],
        ["Reference 18 - Saouli et al.", "volume", "166"],
        ["Reference 18 - Saouli et al.", "pages", "39-49"],

        ["Reference 19 - Lavanyadevi et al.", "topic", "Brain tumor classification and segmentation in MRI images using PNN"],
        ["Reference 19 - Lavanyadevi et al.", "published in", "IEEE ICEICE 2017"],
        ["Reference 19 - Lavanyadevi et al.", "year", "2017"],

        ["Reference 20 - Othman and Basri", "topic", "Probabilistic Neural Network for Brain Tumor Classification"],
        ["Reference 20 - Othman and Basri", "published in", "ISMS 2011"],
        ["Reference 20 - Othman and Basri", "year", "2011"],
        ["Reference 20 - Othman and Basri", "pages", "136-138"],

        ["Reference 21 - Deepa et al.", "topic", "Weiner Filter based Hough Transform and Wavelet feature extraction with Neural Network for Brain Tumor"],
        ["Reference 21 - Deepa et al.", "published in", "ICICT 2021"],
        ["Reference 21 - Deepa et al.", "year", "2021"],
        ["Reference 21 - Deepa et al.", "pages", "637-641"],

        ["Reference 22 - Thara and Jasmine", "topic", "Brain tumour detection in MRI images using PNN and GRNN"],
        ["Reference 22 - Thara and Jasmine", "published in", "WiSPNET 2016"],
        ["Reference 22 - Thara and Jasmine", "year", "2016"],
        ["Reference 22 - Thara and Jasmine", "pages", "1504-1510"],

        ["Reference 23 - Zhang et al.", "topic", "MR Brain Image Classification Based on Adaptive Chaotic PSO"],
        ["Reference 23 - Zhang et al.", "published in", "Progress in Electromagnetics Research"],
        ["Reference 23 - Zhang et al.", "year", "2010"],
        ["Reference 23 - Zhang et al.", "volume", "109"],
        ["Reference 23 - Zhang et al.", "pages", "325-343"],

        ["Reference 24 - Das et al.", "topic", "Detection and area calculation of brain tumor from MRI images using MATLAB"],
        ["Reference 24 - Das et al.", "published in", "International Journal"],
        ["Reference 24 - Das et al.", "year", "2017"],
        ["Reference 24 - Das et al.", "volume", "4(1)"],

        ["Reference 25 - Saraswathi et al.", "topic", "Brain tumor segmentation and classification using self-organizing map"],
        ["Reference 25 - Saraswathi et al.", "published in", "IEEE ICSCAN 2019"],
        ["Reference 25 - Saraswathi et al.", "year", "2019"],
        ["Reference 25 - Saraswathi et al.", "pages", "1-5"],

        ["Reference 26 - Amin et al.", "topic", "Brain tumor detection using statistical and machine learning method"],
        ["Reference 26 - Amin et al.", "published in", "Computer Methods Programs Biomedicine"],
        ["Reference 26 - Amin et al.", "year", "2019"],
        ["Reference 26 - Amin et al.", "volume", "177"],
        ["Reference 26 - Amin et al.", "pages", "69-79"],

        ["Reference 27 - Pandiselvi and Maheswaran", "topic", "Efficient Framework for Identifying, Locating, Detecting and Classifying MRI Brain Tumor"],
        ["Reference 27 - Pandiselvi and Maheswaran", "published in", "Journal of Medical Systems"],
        ["Reference 27 - Pandiselvi and Maheswaran", "year", "2019"],
        ["Reference 27 - Pandiselvi and Maheswaran", "volume", "43(7)"],
        ["Reference 27 - Pandiselvi and Maheswaran", "article ID", "189"]
    ]


    kg = Neo4jKG()

    for t in triples:
        kg.insert_triple(
            t[0].lower(),
            t[1].lower(),
            t[2].lower()
        )

    kg.close()